blank_issues_enabled: true
contact_links:
  - name: Krepto core Security Policy
    url: https://github.com/bitcoin/bitcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Krepto core Developers
    url: https://bitcoincore.org
    about: Krepto core homepage
